[package]
name = "borrowed_with_owner"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stable_deref_trait = "1.2.0"

[workspace]
members = [".", "examples/bump"]

[features]
test_nightly = []
